#!zsh

setopt extendedglob

usage() {
    echo 'Factorio Mod Manager'
    echo 'Usage: $0 \[options\] \[MODID\]'
    echo 'Options:'
    echo '  -h --help                Show this screen'
    echo '  -l --list                List currently enabled and disabled mods'
    echo '     --list-enabled        List only enabled mods'
    echo '     --list-disabled       List only disabled mods'
    echo '  -e --enable (MODID)      Enable mod with specified MODID'
    echo '  -d --disable (MODID)     Disable mod with specified MODID'
    echo '     --save (PRESET_NAME)  Save list of currently enabled and disabled mods'
    echo '     --load (PRESET_NAME)  Load saved list of enabled mods'
}

zparseopts -D -E -- h+=actions -help+=actions\
    l+=actions -list+=actions\
    -list-enabled+=actions -list-disabled+=actions\
    e+:=enable_list -enable+:=enable_list\
    d+:=disable_list -disable+:=disable_list\
    -save:=save_preset_name\
    -load:=load_preset_name

typeset -A CURRENT_MOD_LIST
typeset -a ENABLED_MOD_LIST
typeset -a DISABLED_MOD_LIST

update_mod_list() {
    CURRENT_MOD_LIST=($(jq '.[][][]' ~/.factorio/mods/mod-list.json))
    ENABLED_MOD_LIST=$(jq '.[][] | select(.enabled == true) | .name' ~/.factorio/mods/mod-list.json)
    DISABLED_MOD_LIST=$(jq '.[][] | select(.enabled == false) | .name' ~/.factorio/mods/mod-list.json)
}

get_mod_info() {
    if [[ -f ~/.factorio/mods/"$1"_*.*.*.zip ]] then
        MOD_INFO_JSON=$(7z e -so ~/.factorio/mods/"$1"_*.*.*.zip info.json -r)
    elif [[ -d "~/.factorio/mods/$1" ]] then
        MOD_INFO_JSON=$(cat "~/.factorio/mods/$1/info.json")
    else
        echo "$1 error"
    fi
    MOD_TITLE=$(jq -r '.title' <<< $MOD_INFO_JSON)
    MOD_VERSION=$(jq -r '.version' <<< $MOD_INFO_JSON)
    MOD_IS_ENABLED=$CURRENT_MOD_LIST[$1]
    if [[ $MOD_IS_ENABLED ]] then
        MOD_STATE='enabled'
    else
        MOD_STATE='disabled'
    fi
}

list_mods() {
    update_mod_list
    for MODID MODSTATE in ${(kv)CURRENT_MOD_LIST}; do
        echo 'debug'
        echo "$MODID $MODSTATE"
        get_mod_info $MODID
        echo "$MOD_TITLE $MOD_VERSION \[$MODID\] \($MOD_STATE\)"
    done
}

if [[ ${actions[(ie)'-h']} -le ${#actions} ]] || [[ ${actions[(ie)'--help']} -le ${#actions} ]] then
    usage
elif [[ ${#actions[(ie)'-l']} -le ${#actions} ]] || [[ ${actions[(ie)'--list']} -le ${#actions } ]] then
    list_mods
fi
